// Generated by ReScript, PLEASE EDIT WITH CARE


function fromFloat(prim) {
  return new Date(prim);
}

function valueOf(prim) {
  return prim.valueOf();
}

function toString(prim) {
  return prim.toString();
}

function toStringIso(prim) {
  return prim.toISOString();
}

function toStringDate(prim) {
  return prim.toDateString();
}

function make(prim) {
  return new Date();
}

function now(prim) {
  return Date.now();
}

function fromString(prim) {
  return new Date(prim);
}

function setUTCHoursMSMs(prim0, prim1, prim2, prim3, prim4, prim5) {
  return prim0.setUTCHours(prim1, prim2, prim3, prim4);
}

function setHours(prim0, prim1) {
  return prim0.setHours(prim1);
}

function setMinutes(prim0, prim1) {
  return prim0.setMinutes(prim1);
}

function setSeconds(prim0, prim1) {
  return prim0.setSeconds(prim1);
}

function setMilliseconds(prim0, prim1) {
  return prim0.setMilliseconds(prim1);
}

function setDate(prim0, prim1) {
  return prim0.setDate(prim1);
}

function setTime(prim0, prim1) {
  return prim0.setTime(prim1);
}

var Mut = {
  setHours: setHours,
  setMinutes: setMinutes,
  setSeconds: setSeconds,
  setMilliseconds: setMilliseconds,
  setDate: setDate,
  setTime: setTime
};

function getTime(prim) {
  return prim.getTime();
}

function getDate(prim) {
  return prim.getDate();
}

export {
  fromFloat ,
  valueOf ,
  toString ,
  toStringIso ,
  toStringDate ,
  make ,
  now ,
  fromString ,
  setUTCHoursMSMs ,
  Mut ,
  getTime ,
  getDate ,
}
/* No side effect */
