// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";

function empty(prim) {
  return {};
}

var set = ((dict, key, a) => { return {...dict, [key]: a} });

function getUnsafe(prim0, prim1) {
  return prim0[prim1];
}

var merge = ((dict1, dict2) => { return {...dict1, ...dict2} });

function map(d, fn) {
  return Js_dict.map(fn, d);
}

function set$1(prim0, prim1, prim2) {
  prim0[prim1] = prim2;
}

var Mut = {
  set: set$1
};

var get = Js_dict.get;

var fromArray = Js_dict.fromArray;

var entries = Js_dict.entries;

var values = Js_dict.values;

export {
  empty ,
  set ,
  get ,
  getUnsafe ,
  fromArray ,
  entries ,
  values ,
  merge ,
  map ,
  Mut ,
}
/* No side effect */
