// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";

function message(prim) {
  return prim.message;
}

var raise = Js_exn.raiseError;

export {
  raise ,
  message ,
}
/* No side effect */
