// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Float from "./Float.bs.js";
import * as $$Option from "./Option.bs.js";
import * as Js_math from "rescript/lib/es6/js_math.js";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

function toString(prim) {
  return String(prim);
}

function fromFloat(f) {
  return $$Option.predicate(f, (function (x) {
                return Float.round(f) === x;
              }));
}

function initZeroDigitHelper(num) {
  if (num < 10) {
    return "0" + String(num) + "";
  } else {
    return String(num);
  }
}

function min(prim0, prim1) {
  return Math.min(prim0, prim1);
}

function minMany(prim) {
  return Caml_splice_call.spliceApply(Math.min, [prim]);
}

function max(prim0, prim1) {
  return Math.max(prim0, prim1);
}

function maxMany(prim) {
  return Caml_splice_call.spliceApply(Math.max, [prim]);
}

function abs(prim) {
  return Math.abs(prim);
}

function sign(prim) {
  return Math.sign(prim);
}

function toExponentialWithPrecision(x) {
  return function (param) {
    return x.toExponential(param);
  };
}

var fromString = Belt_Int.fromString;

var random = Js_math.random_int;

export {
  toString ,
  fromString ,
  fromFloat ,
  initZeroDigitHelper ,
  min ,
  minMany ,
  max ,
  maxMany ,
  abs ,
  sign ,
  random ,
  toExponentialWithPrecision ,
}
/* Float Not a pure module */
