// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_json from "rescript/lib/es6/js_json.js";

function stringify(prim) {
  return JSON.stringify(prim);
}

function parseExn(prim) {
  return JSON.parse(prim);
}

function string(prim) {
  return prim;
}

function object_(prim) {
  return prim;
}

function $$boolean(prim) {
  return prim;
}

var $$null = null;

function array(prim) {
  return prim;
}

var decodeObject = Js_json.decodeObject;

var decodeArray = Js_json.decodeArray;

var decodeString = Js_json.decodeString;

var decodeNumber = Js_json.decodeNumber;

var decodeBoolean = Js_json.decodeBoolean;

var decodeNull = Js_json.decodeNull;

var classify = Js_json.classify;

export {
  stringify ,
  parseExn ,
  decodeObject ,
  decodeArray ,
  decodeString ,
  decodeNumber ,
  decodeBoolean ,
  decodeNull ,
  string ,
  object_ ,
  $$boolean ,
  classify ,
  $$null ,
  array ,
}
/* null Not a pure module */
