// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Js_null_undefined from "rescript/lib/es6/js_null_undefined.js";

function toOption(prim) {
  if (prim == null) {
    return ;
  } else {
    return Caml_option.some(prim);
  }
}

function $$return(prim) {
  return prim;
}

var $$null = null;

var fromOption = Js_null_undefined.fromOption;

export {
  $$null ,
  fromOption ,
  toOption ,
  $$return ,
}
/* No side effect */
