// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Option from "./Option.bs.js";
import * as Vitest from "@nobleai/rescript-vitest/src/Vitest.bs.js";
import * as Vitest$1 from "vitest";

Vitest$1.describe("Option", (function (param) {
        Vitest$1.describe("liftA", (function (param) {
                Vitest$1.describe("with a simple function", (function (param) {
                        var f = function (x, y) {
                          return Math.imul(x, y);
                        };
                        Vitest$1.describe("given None", (function (param) {
                                var res = $$Option.liftA2(f, undefined, undefined);
                                Vitest.it("returns None", (function (param) {
                                        Vitest$1.expect(res).toEqual(undefined);
                                      }));
                              }));
                        Vitest$1.describe("given one value", (function (param) {
                                var res = $$Option.liftA2(f, 2, undefined);
                                Vitest.it("returns None", (function (param) {
                                        Vitest$1.expect(res).toEqual(undefined);
                                      }));
                              }));
                        Vitest$1.describe("given two values", (function (param) {
                                var res = $$Option.liftA2(f, 2, 3);
                                Vitest.it("returns Some(f(value))", (function (param) {
                                        Vitest$1.expect(res).toEqual(6);
                                      }));
                              }));
                      }));
              }));
      }));

export {
  
}
/*  Not a pure module */
