// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "@nobleai/rescript-vitest/src/Vitest.bs.js";
import * as Vitest$1 from "vitest";
import * as $$Promise from "./Promise.bs.js";

Vitest$1.describe("Promise", (function (param) {
        Vitest$1.describe("#const", (function (param) {
                var val = "hello";
                var promise = $$Promise.$$return(3);
                var res = $$Promise.$$const(promise, val);
                Vitest.itPromise("should yield val", (function (param) {
                        return $$Promise.tap(res, (function (v) {
                                      Vitest$1.expect(v).toBe(val);
                                    }));
                      }));
              }));
        Vitest$1.describe("#sequence", (function (param) {
                var ins = [
                  1,
                  2,
                  3
                ];
                var fn = function (a) {
                  return $$Promise.$$const($$Promise.sleep(10), a);
                };
                var res = $$Promise.sequence(ins, fn);
                Vitest.itPromise("returns ins in order", (function (param) {
                        return $$Promise.tap(res, (function (res) {
                                      Vitest$1.expect(res).toEqual(ins);
                                    }));
                      }));
              }));
      }));

export {
  
}
/*  Not a pure module */
