// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

function exec_(prim0, prim1) {
  return Caml_option.null_to_opt(prim0.exec(prim1));
}

function fromString(prim) {
  return new RegExp(prim);
}

function captures(prim) {
  return prim;
}

function test_(prim0, prim1) {
  return prim0.test(prim1);
}

export {
  exec_ ,
  fromString ,
  captures ,
  test_ ,
}
/* No side effect */
