// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function make(style, props, children) {
  if (style === undefined) {
    return React.cloneElement(children, props);
  }
  var componet = React.cloneElement(children, props);
  return React.cloneElement(componet, {
              style: style
            });
}

export {
  make ,
}
/* react Not a pure module */
