// Generated by ReScript, PLEASE EDIT WITH CARE


function set(prim0, prim1) {
  return setTimeout(prim0, prim1);
}

function clear(prim) {
  clearTimeout(prim);
}

export {
  set ,
  clear ,
}
/* No side effect */
